### ISSUE TITLE
Incorrect string value: '\xF0\x9F\x98\x8F' for column 'title' at row 1 

### ISSUE THREAD

**Issue by deios0** [akalongman/php-telegram-bot#292]
### Required Information
- PHP version: 7.0
- PHP Telegram Bot version: latest
- Using MySQL database: yes
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

I'm getting strange error occasionally, I even don't know how and then it occurs:

`[2016-09-10 08:42:58] prod.ERROR: ErrorException: PDOStatement::execute(): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8F' for column 'title' at row 1 in /vendor/longman/telegram-bot/src/DB.php:420
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'PDOStatement::e...', '/var/www/...', 420, Array)
#1 /vendor/longman/telegram-bot/src/DB.php(420): PDOStatement->execute()
#2 /vendor/longman/telegram-bot/src/DB.php(683): Longman\TelegramBot\DB::insertChat(Object(Longman\TelegramBot\Entities\Chat), '2016-09-10 06:3...', NULL)
#3 /vendor/longman/telegram-bot/src/DB.php(441): Longman\TelegramBot\DB::insertMessageRequest(Object(Longman\TelegramBot\Entities\Message))
#4 /vendor/longman/telegram-bot/src/Telegram.php(405): Longman\TelegramBot\DB::insertRequest(Object(Longman\TelegramBot\Entities\Update))
#5 /vendor/longman/telegram-bot/src/Telegram.php(340): Longman\TelegramBot\Telegram->processUpdate(Object(Longman\TelegramBot\Entities\Update))`

Could you help with it?

**Comment by deios0** [comment]
Hi?
